*PADS-LIBRARY-PART-TYPES-V9*

header1 header1 M CON 2 0 0 0 0
"Description" Header,vertical,2.54mm pitch;0.635mm lead width,2 pins,2 rows,1 pin per row,2.54mm L X 2.54mm W X 8.38mm H body
"Standard Name" header1

*END*
*REMARK* Generated by LP Wizard 10.3.2
